# Generated by Django 2.0.2 on 2018-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_interest', models.CharField(max_length=255)),
                ('completed', models.DateTimeField(null=True)),
                ('exported', models.DateTimeField(null=True)),
            ],
        ),
    ]
